// Generated by jextract

package llama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct llama_sampler_chain_params {
 *     bool no_perf;
 * }
 * }
 */
public class llama_sampler_chain_params {

    llama_sampler_chain_params() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Llama.C_BOOL.withName("no_perf")
    ).withName("llama_sampler_chain_params");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfBoolean no_perf$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("no_perf"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool no_perf
     * }
     */
    public static final OfBoolean no_perf$layout() {
        return no_perf$LAYOUT;
    }

    private static final long no_perf$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool no_perf
     * }
     */
    public static final long no_perf$offset() {
        return no_perf$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool no_perf
     * }
     */
    public static boolean no_perf(MemorySegment struct) {
        return struct.get(no_perf$LAYOUT, no_perf$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool no_perf
     * }
     */
    public static void no_perf(MemorySegment struct, boolean fieldValue) {
        struct.set(no_perf$LAYOUT, no_perf$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

