// Generated by jextract

package llama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class Llama {

    Llama() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();
    static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

    static void traceDowncall(String name, Object... args) {
         String traceArgs = Arrays.stream(args)
                       .map(Object::toString)
                       .collect(Collectors.joining(", "));
         System.out.printf("%s(%s)\n", name, traceArgs);
    }

    static MemorySegment findOrThrow(String symbol) {
        return SYMBOL_LOOKUP.find(symbol)
            .orElseThrow(() -> new UnsatisfiedLinkError("unresolved symbol: " + symbol));
    }

    static MethodHandle upcallHandle(Class<?> fi, String name, FunctionDescriptor fdesc) {
        try {
            return MethodHandles.lookup().findVirtual(fi, name, fdesc.toMethodType());
        } catch (ReflectiveOperationException ex) {
            throw new AssertionError(ex);
        }
    }

    static MemoryLayout align(MemoryLayout layout, long align) {
        return switch (layout) {
            case PaddingLayout p -> p;
            case ValueLayout v -> v.withByteAlignment(align);
            case GroupLayout g -> {
                MemoryLayout[] alignedMembers = g.memberLayouts().stream()
                        .map(m -> align(m, align)).toArray(MemoryLayout[]::new);
                yield g instanceof StructLayout ?
                        MemoryLayout.structLayout(alignedMembers) : MemoryLayout.unionLayout(alignedMembers);
            }
            case SequenceLayout s -> MemoryLayout.sequenceLayout(s.elementCount(), align(s.elementLayout(), align));
        };
    }

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    public static final ValueLayout.OfBoolean C_BOOL = ValueLayout.JAVA_BOOLEAN;
    public static final ValueLayout.OfByte C_CHAR = ValueLayout.JAVA_BYTE;
    public static final ValueLayout.OfShort C_SHORT = ValueLayout.JAVA_SHORT;
    public static final ValueLayout.OfInt C_INT = ValueLayout.JAVA_INT;
    public static final ValueLayout.OfLong C_LONG_LONG = ValueLayout.JAVA_LONG;
    public static final ValueLayout.OfFloat C_FLOAT = ValueLayout.JAVA_FLOAT;
    public static final ValueLayout.OfDouble C_DOUBLE = ValueLayout.JAVA_DOUBLE;
    public static final AddressLayout C_POINTER = ValueLayout.ADDRESS
            .withTargetLayout(MemoryLayout.sequenceLayout(java.lang.Long.MAX_VALUE, JAVA_BYTE));
    public static final ValueLayout.OfLong C_LONG = ValueLayout.JAVA_LONG;

    private static class ggml_backend_load_all {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(    );

        public static final MemorySegment ADDR = Llama.findOrThrow("ggml_backend_load_all");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern void ggml_backend_load_all()
     * }
     */
    public static FunctionDescriptor ggml_backend_load_all$descriptor() {
        return ggml_backend_load_all.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern void ggml_backend_load_all()
     * }
     */
    public static MethodHandle ggml_backend_load_all$handle() {
        return ggml_backend_load_all.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern void ggml_backend_load_all()
     * }
     */
    public static MemorySegment ggml_backend_load_all$address() {
        return ggml_backend_load_all.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern void ggml_backend_load_all()
     * }
     */
    public static void ggml_backend_load_all() {
        var mh$ = ggml_backend_load_all.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ggml_backend_load_all");
            }
            mh$.invokeExact();
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final int LLAMA_FLASH_ATTN_TYPE_DISABLED = (int)0L;
    /**
     * {@snippet lang=c :
     * enum llama_flash_attn_type.LLAMA_FLASH_ATTN_TYPE_DISABLED = 0
     * }
     */
    public static int LLAMA_FLASH_ATTN_TYPE_DISABLED() {
        return LLAMA_FLASH_ATTN_TYPE_DISABLED;
    }
    private static final int LLAMA_FLASH_ATTN_TYPE_ENABLED = (int)1L;
    /**
     * {@snippet lang=c :
     * enum llama_flash_attn_type.LLAMA_FLASH_ATTN_TYPE_ENABLED = 1
     * }
     */
    public static int LLAMA_FLASH_ATTN_TYPE_ENABLED() {
        return LLAMA_FLASH_ATTN_TYPE_ENABLED;
    }

    private static class llama_model_default_params {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_model_params.layout()    );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_model_default_params");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_model_params llama_model_default_params()
     * }
     */
    public static FunctionDescriptor llama_model_default_params$descriptor() {
        return llama_model_default_params.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_model_params llama_model_default_params()
     * }
     */
    public static MethodHandle llama_model_default_params$handle() {
        return llama_model_default_params.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_model_params llama_model_default_params()
     * }
     */
    public static MemorySegment llama_model_default_params$address() {
        return llama_model_default_params.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_model_params llama_model_default_params()
     * }
     */
    public static MemorySegment llama_model_default_params(SegmentAllocator allocator) {
        var mh$ = llama_model_default_params.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_model_default_params", allocator);
            }
            return (MemorySegment)mh$.invokeExact(allocator);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_context_default_params {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_context_params.layout()    );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_context_default_params");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_context_params llama_context_default_params()
     * }
     */
    public static FunctionDescriptor llama_context_default_params$descriptor() {
        return llama_context_default_params.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_context_params llama_context_default_params()
     * }
     */
    public static MethodHandle llama_context_default_params$handle() {
        return llama_context_default_params.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_context_params llama_context_default_params()
     * }
     */
    public static MemorySegment llama_context_default_params$address() {
        return llama_context_default_params.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_context_params llama_context_default_params()
     * }
     */
    public static MemorySegment llama_context_default_params(SegmentAllocator allocator) {
        var mh$ = llama_context_default_params.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_context_default_params", allocator);
            }
            return (MemorySegment)mh$.invokeExact(allocator);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_sampler_chain_default_params {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_sampler_chain_params.layout()    );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_sampler_chain_default_params");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_sampler_chain_params llama_sampler_chain_default_params()
     * }
     */
    public static FunctionDescriptor llama_sampler_chain_default_params$descriptor() {
        return llama_sampler_chain_default_params.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_sampler_chain_params llama_sampler_chain_default_params()
     * }
     */
    public static MethodHandle llama_sampler_chain_default_params$handle() {
        return llama_sampler_chain_default_params.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_sampler_chain_params llama_sampler_chain_default_params()
     * }
     */
    public static MemorySegment llama_sampler_chain_default_params$address() {
        return llama_sampler_chain_default_params.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_sampler_chain_params llama_sampler_chain_default_params()
     * }
     */
    public static MemorySegment llama_sampler_chain_default_params(SegmentAllocator allocator) {
        var mh$ = llama_sampler_chain_default_params.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_sampler_chain_default_params", allocator);
            }
            return (MemorySegment)mh$.invokeExact(allocator);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_backend_init {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(    );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_backend_init");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_backend_init()
     * }
     */
    public static FunctionDescriptor llama_backend_init$descriptor() {
        return llama_backend_init.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_backend_init()
     * }
     */
    public static MethodHandle llama_backend_init$handle() {
        return llama_backend_init.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_backend_init()
     * }
     */
    public static MemorySegment llama_backend_init$address() {
        return llama_backend_init.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_backend_init()
     * }
     */
    public static void llama_backend_init() {
        var mh$ = llama_backend_init.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_backend_init");
            }
            mh$.invokeExact();
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_backend_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(    );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_backend_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_backend_free()
     * }
     */
    public static FunctionDescriptor llama_backend_free$descriptor() {
        return llama_backend_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_backend_free()
     * }
     */
    public static MethodHandle llama_backend_free$handle() {
        return llama_backend_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_backend_free()
     * }
     */
    public static MemorySegment llama_backend_free$address() {
        return llama_backend_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_backend_free()
     * }
     */
    public static void llama_backend_free() {
        var mh$ = llama_backend_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_backend_free");
            }
            mh$.invokeExact();
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_model_load_from_file {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Llama.C_POINTER,
            Llama.C_POINTER,
            llama_model_params.layout()
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_model_load_from_file");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_model *llama_model_load_from_file(const char *path_model, struct llama_model_params params)
     * }
     */
    public static FunctionDescriptor llama_model_load_from_file$descriptor() {
        return llama_model_load_from_file.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_model *llama_model_load_from_file(const char *path_model, struct llama_model_params params)
     * }
     */
    public static MethodHandle llama_model_load_from_file$handle() {
        return llama_model_load_from_file.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_model *llama_model_load_from_file(const char *path_model, struct llama_model_params params)
     * }
     */
    public static MemorySegment llama_model_load_from_file$address() {
        return llama_model_load_from_file.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_model *llama_model_load_from_file(const char *path_model, struct llama_model_params params)
     * }
     */
    public static MemorySegment llama_model_load_from_file(MemorySegment path_model, MemorySegment params) {
        var mh$ = llama_model_load_from_file.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_model_load_from_file", path_model, params);
            }
            return (MemorySegment)mh$.invokeExact(path_model, params);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_model_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            Llama.C_POINTER
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_model_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_model_free(struct llama_model *model)
     * }
     */
    public static FunctionDescriptor llama_model_free$descriptor() {
        return llama_model_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_model_free(struct llama_model *model)
     * }
     */
    public static MethodHandle llama_model_free$handle() {
        return llama_model_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_model_free(struct llama_model *model)
     * }
     */
    public static MemorySegment llama_model_free$address() {
        return llama_model_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_model_free(struct llama_model *model)
     * }
     */
    public static void llama_model_free(MemorySegment model) {
        var mh$ = llama_model_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_model_free", model);
            }
            mh$.invokeExact(model);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_init_from_model {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Llama.C_POINTER,
            Llama.C_POINTER,
            llama_context_params.layout()
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_init_from_model");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_context *llama_init_from_model(struct llama_model *model, struct llama_context_params params)
     * }
     */
    public static FunctionDescriptor llama_init_from_model$descriptor() {
        return llama_init_from_model.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_context *llama_init_from_model(struct llama_model *model, struct llama_context_params params)
     * }
     */
    public static MethodHandle llama_init_from_model$handle() {
        return llama_init_from_model.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_context *llama_init_from_model(struct llama_model *model, struct llama_context_params params)
     * }
     */
    public static MemorySegment llama_init_from_model$address() {
        return llama_init_from_model.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_context *llama_init_from_model(struct llama_model *model, struct llama_context_params params)
     * }
     */
    public static MemorySegment llama_init_from_model(MemorySegment model, MemorySegment params) {
        var mh$ = llama_init_from_model.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_init_from_model", model, params);
            }
            return (MemorySegment)mh$.invokeExact(model, params);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            Llama.C_POINTER
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_free(struct llama_context *ctx)
     * }
     */
    public static FunctionDescriptor llama_free$descriptor() {
        return llama_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_free(struct llama_context *ctx)
     * }
     */
    public static MethodHandle llama_free$handle() {
        return llama_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_free(struct llama_context *ctx)
     * }
     */
    public static MemorySegment llama_free$address() {
        return llama_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_free(struct llama_context *ctx)
     * }
     */
    public static void llama_free(MemorySegment ctx) {
        var mh$ = llama_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_free", ctx);
            }
            mh$.invokeExact(ctx);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_get_memory {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Llama.C_POINTER,
            Llama.C_POINTER
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_get_memory");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * llama_memory_t llama_get_memory(const struct llama_context *ctx)
     * }
     */
    public static FunctionDescriptor llama_get_memory$descriptor() {
        return llama_get_memory.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * llama_memory_t llama_get_memory(const struct llama_context *ctx)
     * }
     */
    public static MethodHandle llama_get_memory$handle() {
        return llama_get_memory.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * llama_memory_t llama_get_memory(const struct llama_context *ctx)
     * }
     */
    public static MemorySegment llama_get_memory$address() {
        return llama_get_memory.ADDR;
    }

    /**
     * {@snippet lang=c :
     * llama_memory_t llama_get_memory(const struct llama_context *ctx)
     * }
     */
    public static MemorySegment llama_get_memory(MemorySegment ctx) {
        var mh$ = llama_get_memory.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_get_memory", ctx);
            }
            return (MemorySegment)mh$.invokeExact(ctx);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_model_get_vocab {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Llama.C_POINTER,
            Llama.C_POINTER
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_model_get_vocab");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const struct llama_vocab *llama_model_get_vocab(const struct llama_model *model)
     * }
     */
    public static FunctionDescriptor llama_model_get_vocab$descriptor() {
        return llama_model_get_vocab.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const struct llama_vocab *llama_model_get_vocab(const struct llama_model *model)
     * }
     */
    public static MethodHandle llama_model_get_vocab$handle() {
        return llama_model_get_vocab.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const struct llama_vocab *llama_model_get_vocab(const struct llama_model *model)
     * }
     */
    public static MemorySegment llama_model_get_vocab$address() {
        return llama_model_get_vocab.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const struct llama_vocab *llama_model_get_vocab(const struct llama_model *model)
     * }
     */
    public static MemorySegment llama_model_get_vocab(MemorySegment model) {
        var mh$ = llama_model_get_vocab.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_model_get_vocab", model);
            }
            return (MemorySegment)mh$.invokeExact(model);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_vocab_n_tokens {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Llama.C_INT,
            Llama.C_POINTER
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_vocab_n_tokens");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t llama_vocab_n_tokens(const struct llama_vocab *vocab)
     * }
     */
    public static FunctionDescriptor llama_vocab_n_tokens$descriptor() {
        return llama_vocab_n_tokens.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t llama_vocab_n_tokens(const struct llama_vocab *vocab)
     * }
     */
    public static MethodHandle llama_vocab_n_tokens$handle() {
        return llama_vocab_n_tokens.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t llama_vocab_n_tokens(const struct llama_vocab *vocab)
     * }
     */
    public static MemorySegment llama_vocab_n_tokens$address() {
        return llama_vocab_n_tokens.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t llama_vocab_n_tokens(const struct llama_vocab *vocab)
     * }
     */
    public static int llama_vocab_n_tokens(MemorySegment vocab) {
        var mh$ = llama_vocab_n_tokens.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_vocab_n_tokens", vocab);
            }
            return (int)mh$.invokeExact(vocab);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_memory_clear {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            Llama.C_POINTER,
            Llama.C_BOOL
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_memory_clear");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_memory_clear(llama_memory_t mem, bool data)
     * }
     */
    public static FunctionDescriptor llama_memory_clear$descriptor() {
        return llama_memory_clear.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_memory_clear(llama_memory_t mem, bool data)
     * }
     */
    public static MethodHandle llama_memory_clear$handle() {
        return llama_memory_clear.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_memory_clear(llama_memory_t mem, bool data)
     * }
     */
    public static MemorySegment llama_memory_clear$address() {
        return llama_memory_clear.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_memory_clear(llama_memory_t mem, bool data)
     * }
     */
    public static void llama_memory_clear(MemorySegment mem, boolean data) {
        var mh$ = llama_memory_clear.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_memory_clear", mem, data);
            }
            mh$.invokeExact(mem, data);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_memory_seq_rm {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Llama.C_BOOL,
            Llama.C_POINTER,
            Llama.C_INT,
            Llama.C_INT,
            Llama.C_INT
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_memory_seq_rm");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * bool llama_memory_seq_rm(llama_memory_t mem, llama_seq_id seq_id, llama_pos p0, llama_pos p1)
     * }
     */
    public static FunctionDescriptor llama_memory_seq_rm$descriptor() {
        return llama_memory_seq_rm.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * bool llama_memory_seq_rm(llama_memory_t mem, llama_seq_id seq_id, llama_pos p0, llama_pos p1)
     * }
     */
    public static MethodHandle llama_memory_seq_rm$handle() {
        return llama_memory_seq_rm.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * bool llama_memory_seq_rm(llama_memory_t mem, llama_seq_id seq_id, llama_pos p0, llama_pos p1)
     * }
     */
    public static MemorySegment llama_memory_seq_rm$address() {
        return llama_memory_seq_rm.ADDR;
    }

    /**
     * {@snippet lang=c :
     * bool llama_memory_seq_rm(llama_memory_t mem, llama_seq_id seq_id, llama_pos p0, llama_pos p1)
     * }
     */
    public static boolean llama_memory_seq_rm(MemorySegment mem, int seq_id, int p0, int p1) {
        var mh$ = llama_memory_seq_rm.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_memory_seq_rm", mem, seq_id, p0, p1);
            }
            return (boolean)mh$.invokeExact(mem, seq_id, p0, p1);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_memory_seq_cp {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            Llama.C_POINTER,
            Llama.C_INT,
            Llama.C_INT,
            Llama.C_INT,
            Llama.C_INT
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_memory_seq_cp");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_memory_seq_cp(llama_memory_t mem, llama_seq_id seq_id_src, llama_seq_id seq_id_dst, llama_pos p0, llama_pos p1)
     * }
     */
    public static FunctionDescriptor llama_memory_seq_cp$descriptor() {
        return llama_memory_seq_cp.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_memory_seq_cp(llama_memory_t mem, llama_seq_id seq_id_src, llama_seq_id seq_id_dst, llama_pos p0, llama_pos p1)
     * }
     */
    public static MethodHandle llama_memory_seq_cp$handle() {
        return llama_memory_seq_cp.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_memory_seq_cp(llama_memory_t mem, llama_seq_id seq_id_src, llama_seq_id seq_id_dst, llama_pos p0, llama_pos p1)
     * }
     */
    public static MemorySegment llama_memory_seq_cp$address() {
        return llama_memory_seq_cp.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_memory_seq_cp(llama_memory_t mem, llama_seq_id seq_id_src, llama_seq_id seq_id_dst, llama_pos p0, llama_pos p1)
     * }
     */
    public static void llama_memory_seq_cp(MemorySegment mem, int seq_id_src, int seq_id_dst, int p0, int p1) {
        var mh$ = llama_memory_seq_cp.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_memory_seq_cp", mem, seq_id_src, seq_id_dst, p0, p1);
            }
            mh$.invokeExact(mem, seq_id_src, seq_id_dst, p0, p1);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_batch_init {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_batch.layout(),
            Llama.C_INT,
            Llama.C_INT,
            Llama.C_INT
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_batch_init");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_batch llama_batch_init(int32_t n_tokens, int32_t embd, int32_t n_seq_max)
     * }
     */
    public static FunctionDescriptor llama_batch_init$descriptor() {
        return llama_batch_init.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_batch llama_batch_init(int32_t n_tokens, int32_t embd, int32_t n_seq_max)
     * }
     */
    public static MethodHandle llama_batch_init$handle() {
        return llama_batch_init.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_batch llama_batch_init(int32_t n_tokens, int32_t embd, int32_t n_seq_max)
     * }
     */
    public static MemorySegment llama_batch_init$address() {
        return llama_batch_init.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_batch llama_batch_init(int32_t n_tokens, int32_t embd, int32_t n_seq_max)
     * }
     */
    public static MemorySegment llama_batch_init(SegmentAllocator allocator, int n_tokens, int embd, int n_seq_max) {
        var mh$ = llama_batch_init.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_batch_init", allocator, n_tokens, embd, n_seq_max);
            }
            return (MemorySegment)mh$.invokeExact(allocator, n_tokens, embd, n_seq_max);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_batch_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            llama_batch.layout()
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_batch_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_batch_free(struct llama_batch batch)
     * }
     */
    public static FunctionDescriptor llama_batch_free$descriptor() {
        return llama_batch_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_batch_free(struct llama_batch batch)
     * }
     */
    public static MethodHandle llama_batch_free$handle() {
        return llama_batch_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_batch_free(struct llama_batch batch)
     * }
     */
    public static MemorySegment llama_batch_free$address() {
        return llama_batch_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_batch_free(struct llama_batch batch)
     * }
     */
    public static void llama_batch_free(MemorySegment batch) {
        var mh$ = llama_batch_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_batch_free", batch);
            }
            mh$.invokeExact(batch);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_decode {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Llama.C_INT,
            Llama.C_POINTER,
            llama_batch.layout()
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_decode");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t llama_decode(struct llama_context *ctx, struct llama_batch batch)
     * }
     */
    public static FunctionDescriptor llama_decode$descriptor() {
        return llama_decode.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t llama_decode(struct llama_context *ctx, struct llama_batch batch)
     * }
     */
    public static MethodHandle llama_decode$handle() {
        return llama_decode.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t llama_decode(struct llama_context *ctx, struct llama_batch batch)
     * }
     */
    public static MemorySegment llama_decode$address() {
        return llama_decode.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t llama_decode(struct llama_context *ctx, struct llama_batch batch)
     * }
     */
    public static int llama_decode(MemorySegment ctx, MemorySegment batch) {
        var mh$ = llama_decode.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_decode", ctx, batch);
            }
            return (int)mh$.invokeExact(ctx, batch);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_synchronize {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            Llama.C_POINTER
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_synchronize");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_synchronize(struct llama_context *ctx)
     * }
     */
    public static FunctionDescriptor llama_synchronize$descriptor() {
        return llama_synchronize.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_synchronize(struct llama_context *ctx)
     * }
     */
    public static MethodHandle llama_synchronize$handle() {
        return llama_synchronize.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_synchronize(struct llama_context *ctx)
     * }
     */
    public static MemorySegment llama_synchronize$address() {
        return llama_synchronize.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_synchronize(struct llama_context *ctx)
     * }
     */
    public static void llama_synchronize(MemorySegment ctx) {
        var mh$ = llama_synchronize.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_synchronize", ctx);
            }
            mh$.invokeExact(ctx);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_get_logits_ith {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Llama.C_POINTER,
            Llama.C_POINTER,
            Llama.C_INT
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_get_logits_ith");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * float *llama_get_logits_ith(struct llama_context *ctx, int32_t i)
     * }
     */
    public static FunctionDescriptor llama_get_logits_ith$descriptor() {
        return llama_get_logits_ith.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * float *llama_get_logits_ith(struct llama_context *ctx, int32_t i)
     * }
     */
    public static MethodHandle llama_get_logits_ith$handle() {
        return llama_get_logits_ith.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * float *llama_get_logits_ith(struct llama_context *ctx, int32_t i)
     * }
     */
    public static MemorySegment llama_get_logits_ith$address() {
        return llama_get_logits_ith.ADDR;
    }

    /**
     * {@snippet lang=c :
     * float *llama_get_logits_ith(struct llama_context *ctx, int32_t i)
     * }
     */
    public static MemorySegment llama_get_logits_ith(MemorySegment ctx, int i) {
        var mh$ = llama_get_logits_ith.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_get_logits_ith", ctx, i);
            }
            return (MemorySegment)mh$.invokeExact(ctx, i);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_vocab_is_eog {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Llama.C_BOOL,
            Llama.C_POINTER,
            Llama.C_INT
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_vocab_is_eog");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * bool llama_vocab_is_eog(const struct llama_vocab *vocab, llama_token token)
     * }
     */
    public static FunctionDescriptor llama_vocab_is_eog$descriptor() {
        return llama_vocab_is_eog.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * bool llama_vocab_is_eog(const struct llama_vocab *vocab, llama_token token)
     * }
     */
    public static MethodHandle llama_vocab_is_eog$handle() {
        return llama_vocab_is_eog.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * bool llama_vocab_is_eog(const struct llama_vocab *vocab, llama_token token)
     * }
     */
    public static MemorySegment llama_vocab_is_eog$address() {
        return llama_vocab_is_eog.ADDR;
    }

    /**
     * {@snippet lang=c :
     * bool llama_vocab_is_eog(const struct llama_vocab *vocab, llama_token token)
     * }
     */
    public static boolean llama_vocab_is_eog(MemorySegment vocab, int token) {
        var mh$ = llama_vocab_is_eog.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_vocab_is_eog", vocab, token);
            }
            return (boolean)mh$.invokeExact(vocab, token);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_tokenize {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Llama.C_INT,
            Llama.C_POINTER,
            Llama.C_POINTER,
            Llama.C_INT,
            Llama.C_POINTER,
            Llama.C_INT,
            Llama.C_BOOL,
            Llama.C_BOOL
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_tokenize");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t llama_tokenize(const struct llama_vocab *vocab, const char *text, int32_t text_len, llama_token *tokens, int32_t n_tokens_max, bool add_special, bool parse_special)
     * }
     */
    public static FunctionDescriptor llama_tokenize$descriptor() {
        return llama_tokenize.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t llama_tokenize(const struct llama_vocab *vocab, const char *text, int32_t text_len, llama_token *tokens, int32_t n_tokens_max, bool add_special, bool parse_special)
     * }
     */
    public static MethodHandle llama_tokenize$handle() {
        return llama_tokenize.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t llama_tokenize(const struct llama_vocab *vocab, const char *text, int32_t text_len, llama_token *tokens, int32_t n_tokens_max, bool add_special, bool parse_special)
     * }
     */
    public static MemorySegment llama_tokenize$address() {
        return llama_tokenize.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t llama_tokenize(const struct llama_vocab *vocab, const char *text, int32_t text_len, llama_token *tokens, int32_t n_tokens_max, bool add_special, bool parse_special)
     * }
     */
    public static int llama_tokenize(MemorySegment vocab, MemorySegment text, int text_len, MemorySegment tokens, int n_tokens_max, boolean add_special, boolean parse_special) {
        var mh$ = llama_tokenize.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_tokenize", vocab, text, text_len, tokens, n_tokens_max, add_special, parse_special);
            }
            return (int)mh$.invokeExact(vocab, text, text_len, tokens, n_tokens_max, add_special, parse_special);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_token_to_piece {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Llama.C_INT,
            Llama.C_POINTER,
            Llama.C_INT,
            Llama.C_POINTER,
            Llama.C_INT,
            Llama.C_INT,
            Llama.C_BOOL
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_token_to_piece");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t llama_token_to_piece(const struct llama_vocab *vocab, llama_token token, char *buf, int32_t length, int32_t lstrip, bool special)
     * }
     */
    public static FunctionDescriptor llama_token_to_piece$descriptor() {
        return llama_token_to_piece.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t llama_token_to_piece(const struct llama_vocab *vocab, llama_token token, char *buf, int32_t length, int32_t lstrip, bool special)
     * }
     */
    public static MethodHandle llama_token_to_piece$handle() {
        return llama_token_to_piece.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t llama_token_to_piece(const struct llama_vocab *vocab, llama_token token, char *buf, int32_t length, int32_t lstrip, bool special)
     * }
     */
    public static MemorySegment llama_token_to_piece$address() {
        return llama_token_to_piece.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t llama_token_to_piece(const struct llama_vocab *vocab, llama_token token, char *buf, int32_t length, int32_t lstrip, bool special)
     * }
     */
    public static int llama_token_to_piece(MemorySegment vocab, int token, MemorySegment buf, int length, int lstrip, boolean special) {
        var mh$ = llama_token_to_piece.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_token_to_piece", vocab, token, buf, length, lstrip, special);
            }
            return (int)mh$.invokeExact(vocab, token, buf, length, lstrip, special);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_sampler_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            Llama.C_POINTER
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_sampler_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_sampler_free(struct llama_sampler *smpl)
     * }
     */
    public static FunctionDescriptor llama_sampler_free$descriptor() {
        return llama_sampler_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_sampler_free(struct llama_sampler *smpl)
     * }
     */
    public static MethodHandle llama_sampler_free$handle() {
        return llama_sampler_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_sampler_free(struct llama_sampler *smpl)
     * }
     */
    public static MemorySegment llama_sampler_free$address() {
        return llama_sampler_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_sampler_free(struct llama_sampler *smpl)
     * }
     */
    public static void llama_sampler_free(MemorySegment smpl) {
        var mh$ = llama_sampler_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_sampler_free", smpl);
            }
            mh$.invokeExact(smpl);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_sampler_chain_init {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Llama.C_POINTER,
            llama_sampler_chain_params.layout()
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_sampler_chain_init");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_chain_init(struct llama_sampler_chain_params params)
     * }
     */
    public static FunctionDescriptor llama_sampler_chain_init$descriptor() {
        return llama_sampler_chain_init.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_chain_init(struct llama_sampler_chain_params params)
     * }
     */
    public static MethodHandle llama_sampler_chain_init$handle() {
        return llama_sampler_chain_init.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_chain_init(struct llama_sampler_chain_params params)
     * }
     */
    public static MemorySegment llama_sampler_chain_init$address() {
        return llama_sampler_chain_init.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_chain_init(struct llama_sampler_chain_params params)
     * }
     */
    public static MemorySegment llama_sampler_chain_init(MemorySegment params) {
        var mh$ = llama_sampler_chain_init.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_sampler_chain_init", params);
            }
            return (MemorySegment)mh$.invokeExact(params);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_sampler_chain_add {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            Llama.C_POINTER,
            Llama.C_POINTER
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_sampler_chain_add");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_sampler_chain_add(struct llama_sampler *chain, struct llama_sampler *smpl)
     * }
     */
    public static FunctionDescriptor llama_sampler_chain_add$descriptor() {
        return llama_sampler_chain_add.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_sampler_chain_add(struct llama_sampler *chain, struct llama_sampler *smpl)
     * }
     */
    public static MethodHandle llama_sampler_chain_add$handle() {
        return llama_sampler_chain_add.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_sampler_chain_add(struct llama_sampler *chain, struct llama_sampler *smpl)
     * }
     */
    public static MemorySegment llama_sampler_chain_add$address() {
        return llama_sampler_chain_add.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_sampler_chain_add(struct llama_sampler *chain, struct llama_sampler *smpl)
     * }
     */
    public static void llama_sampler_chain_add(MemorySegment chain, MemorySegment smpl) {
        var mh$ = llama_sampler_chain_add.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_sampler_chain_add", chain, smpl);
            }
            mh$.invokeExact(chain, smpl);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_sampler_init_greedy {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Llama.C_POINTER    );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_sampler_init_greedy");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_greedy()
     * }
     */
    public static FunctionDescriptor llama_sampler_init_greedy$descriptor() {
        return llama_sampler_init_greedy.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_greedy()
     * }
     */
    public static MethodHandle llama_sampler_init_greedy$handle() {
        return llama_sampler_init_greedy.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_greedy()
     * }
     */
    public static MemorySegment llama_sampler_init_greedy$address() {
        return llama_sampler_init_greedy.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_greedy()
     * }
     */
    public static MemorySegment llama_sampler_init_greedy() {
        var mh$ = llama_sampler_init_greedy.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_sampler_init_greedy");
            }
            return (MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_sampler_init_grammar {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Llama.C_POINTER,
            Llama.C_POINTER,
            Llama.C_POINTER,
            Llama.C_POINTER
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_sampler_init_grammar");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_grammar(const struct llama_vocab *vocab, const char *grammar_str, const char *grammar_root)
     * }
     */
    public static FunctionDescriptor llama_sampler_init_grammar$descriptor() {
        return llama_sampler_init_grammar.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_grammar(const struct llama_vocab *vocab, const char *grammar_str, const char *grammar_root)
     * }
     */
    public static MethodHandle llama_sampler_init_grammar$handle() {
        return llama_sampler_init_grammar.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_grammar(const struct llama_vocab *vocab, const char *grammar_str, const char *grammar_root)
     * }
     */
    public static MemorySegment llama_sampler_init_grammar$address() {
        return llama_sampler_init_grammar.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_grammar(const struct llama_vocab *vocab, const char *grammar_str, const char *grammar_root)
     * }
     */
    public static MemorySegment llama_sampler_init_grammar(MemorySegment vocab, MemorySegment grammar_str, MemorySegment grammar_root) {
        var mh$ = llama_sampler_init_grammar.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_sampler_init_grammar", vocab, grammar_str, grammar_root);
            }
            return (MemorySegment)mh$.invokeExact(vocab, grammar_str, grammar_root);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_sampler_sample {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Llama.C_INT,
            Llama.C_POINTER,
            Llama.C_POINTER,
            Llama.C_INT
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_sampler_sample");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * llama_token llama_sampler_sample(struct llama_sampler *smpl, struct llama_context *ctx, int32_t idx)
     * }
     */
    public static FunctionDescriptor llama_sampler_sample$descriptor() {
        return llama_sampler_sample.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * llama_token llama_sampler_sample(struct llama_sampler *smpl, struct llama_context *ctx, int32_t idx)
     * }
     */
    public static MethodHandle llama_sampler_sample$handle() {
        return llama_sampler_sample.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * llama_token llama_sampler_sample(struct llama_sampler *smpl, struct llama_context *ctx, int32_t idx)
     * }
     */
    public static MemorySegment llama_sampler_sample$address() {
        return llama_sampler_sample.ADDR;
    }

    /**
     * {@snippet lang=c :
     * llama_token llama_sampler_sample(struct llama_sampler *smpl, struct llama_context *ctx, int32_t idx)
     * }
     */
    public static int llama_sampler_sample(MemorySegment smpl, MemorySegment ctx, int idx) {
        var mh$ = llama_sampler_sample.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_sampler_sample", smpl, ctx, idx);
            }
            return (int)mh$.invokeExact(smpl, ctx, idx);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_log_set {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            Llama.C_POINTER,
            Llama.C_POINTER
        );

        public static final MemorySegment ADDR = Llama.findOrThrow("llama_log_set");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_log_set(ggml_log_callback log_callback, void *user_data)
     * }
     */
    public static FunctionDescriptor llama_log_set$descriptor() {
        return llama_log_set.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_log_set(ggml_log_callback log_callback, void *user_data)
     * }
     */
    public static MethodHandle llama_log_set$handle() {
        return llama_log_set.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_log_set(ggml_log_callback log_callback, void *user_data)
     * }
     */
    public static MemorySegment llama_log_set$address() {
        return llama_log_set.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_log_set(ggml_log_callback log_callback, void *user_data)
     * }
     */
    public static void llama_log_set(MemorySegment log_callback, MemorySegment user_data) {
        var mh$ = llama_log_set.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_log_set", log_callback, user_data);
            }
            mh$.invokeExact(log_callback, user_data);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}
